# Generated by Django 2.2.10 on 2020-02-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0002_auto_20200210_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='mather_phno',
            new_name='mother_phno',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
    ]
