# Generated by Django 2.2.10 on 2020-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0003_auto_20200210_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='rishabdesai7@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
