# Generated by Django 2.2.10 on 2020-02-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0004_auto_20200210_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='rollno',
            new_name='idno',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='adhaar_card',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='current_add',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='current_add_pincode',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='father_phno',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='mother_phno',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='permanent_add',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='permanent_add_pincode',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('F', 'Faculty')], default='S', max_length=10),
            preserve_default=False,
        ),
    ]
