# Generated by Django 2.2.10 on 2020-02-11 16:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0005_auto_20200211_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phno', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('type', models.CharField(choices=[('S', 'Student'), ('F', 'Faculty')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
