# Generated by Django 2.2.10 on 2020-02-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0006_auto_20200211_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='idno',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
