# Generated by Django 2.2.10 on 2020-02-18 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colcon', '0009_channelrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(max_length=100)),
                ('against_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colcon.Channel')),
                ('against_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colcon.Profile')),
                ('by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
