# Generated by Django 2.2.10 on 2020-02-18 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colcon', '0010_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Complaint',
        ),
    ]
