# Generated by Django 2.2.10 on 2020-02-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0011_auto_20200218_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
