# Generated by Django 2.2.10 on 2020-02-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0014_auto_20200218_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='against_channel',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='colcon.Channel'),
            preserve_default=False,
        ),
    ]
