# Generated by Django 2.2.10 on 2020-02-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0015_complaints_against_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='against_channel',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='colcon.Channel'),
        ),
    ]
