# Generated by Django 2.2.10 on 2020-02-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0016_auto_20200218_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='against_person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='colcon.Profile'),
        ),
    ]
