# Generated by Django 2.2.10 on 2020-02-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colcon', '0017_complaints_against_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='by',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='against_channel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='against_person',
            field=models.CharField(max_length=20),
        ),
    ]
