# Generated by Django 2.2.10 on 2020-02-18 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colcon', '0018_auto_20200218_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against_person', models.CharField(max_length=20)),
                ('against_channel', models.CharField(max_length=20)),
                ('issue', models.TextField(max_length=500)),
                ('by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
