# Generated by Django 2.2.10 on 2020-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0021_auto_20200218_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitations',
            field=models.ManyToManyField(related_name='invitation', to='colcon.Channel'),
        ),
    ]
