# Generated by Django 2.2.10 on 2020-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colcon', '0022_profile_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='dept',
            field=models.CharField(default='IT', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sec',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
